# Generated by Django 4.2.3 on 2024-01-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ahmedabad', models.IntegerField()),
                ('Rajkot', models.IntegerField()),
                ('Mumbai', models.IntegerField()),
                ('Jamnagar', models.IntegerField()),
                ('Khambhaliya', models.IntegerField()),
                ('Surat', models.IntegerField()),
                ('Baroda', models.IntegerField()),
                ('Junagadh', models.IntegerField()),
                ('SavarKundla', models.IntegerField()),
                ('Viramgam', models.IntegerField()),
                ('Wankaner', models.IntegerField()),
                ('Amreli', models.IntegerField()),
                ('Gondal', models.IntegerField()),
                ('Jetpur', models.IntegerField()),
                ('Porbandar', models.IntegerField()),
                ('Bhavnagar', models.IntegerField()),
                ('Veraval', models.IntegerField()),
                ('Talala_Gir', models.IntegerField()),
                ('Una', models.IntegerField()),
                ('Kodinar', models.IntegerField()),
                ('Dwarka', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('quantityIn', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('Mo_No', models.IntegerField()),
                ('quant', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('Choice', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('Mo_No', models.IntegerField()),
                ('quant', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('Choice', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('total_price', models.FloatField()),
                ('payment_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
