# Generated by Django 4.2.3 on 2024-01-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MangoliciousApp', '0002_alter_details_payment_id_alter_details_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='created_at',
        ),
    ]
