# Generated by Django 3.2.12 on 2024-04-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MangoliciousApp', '0004_ripemangoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='typeofmangoes',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
